# Generated by Django 6.0.3 on 2026-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='description',
            field=models.TextField(default='no description provided'),
        ),
    ]
