# Generated by Django 6.0.3 on 2026-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_careerroadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming Language', 'Programming language'), ('Framework', 'Framework'), ('Databases', 'Databases'), ('Tool', 'Tool'), ('Soft skill', 'Soft skill'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=200),
        ),
    ]
