# Generated by Django 6.0.3 on 2026-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_userskill_category_alter_userskill_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='category',
            field=models.CharField(blank=True, choices=[('Programming Language', 'Programming language'), ('Framework', 'Framework'), ('Databases', 'Databases'), ('Tool', 'Tool'), ('Soft skill', 'Soft Skill'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
