# Generated by Django 6.0.3 on 2026-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_userskill_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpath',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='careerpath',
            old_name='required_tools',
            new_name='tools_required',
        ),
        migrations.AddField(
            model_name='careerpath',
            name='application_area',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='recommended_learning_path',
            field=models.TextField(blank=True),
        ),
    ]
