# Generated by Django 6.0.3 on 2026-04-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_rename_name_careerpath_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerroadmap',
            name='career',
        ),
        migrations.RemoveField(
            model_name='careerroadmap',
            name='skill',
        ),
        migrations.DeleteModel(
            name='CareerPath',
        ),
        migrations.DeleteModel(
            name='CareerRoadmap',
        ),
    ]
