# Generated by Django 6.0.3 on 2026-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_remove_careerroadmap_career_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('tools_needed', models.TextField()),
                ('application_area', models.TextField()),
                ('recommended_learning_path', models.TextField()),
                ('skills_required', models.ManyToManyField(related_name='career_paths', to='skills.skill')),
            ],
        ),
        migrations.DeleteModel(
            name='TechnologyTool',
        ),
    ]
