# Generated by Django 6.0.3 on 2026-04-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_careerpath_delete_technologytool'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
