# Generated by Django 6.0.3 on 2026-05-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_careerpath_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerpath',
            name='application_area',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='recommended_learning_path',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='skills_required',
        ),
        migrations.RemoveField(
            model_name='careerpath',
            name='tools_needed',
        ),
    ]
