# Generated by Django 6.0.3 on 2026-05-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_remove_careerpath_application_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='applications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='industries',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='salary',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='careerpath',
            name='tools_needed',
            field=models.JSONField(default=list),
        ),
    ]
