# Generated by Django 6.0.3 on 2026-05-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_careerpath_applications_careerpath_industries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerpath',
            old_name='skills',
            new_name='skills_required',
        ),
    ]
