# Generated by Django 6.0.3 on 2026-05-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0014_rename_skills_careerpath_skills_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('careerpath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to='skills.careerpath')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='skills.learningstage')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='skills.learningstage')),
            ],
        ),
    ]
