# Generated by Django 5.2.7 on 2026-05-13 21:00

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fix_superuser_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
